services:
  app:
    build: .
    image: kyoungyeob/tiny-inventory-management-app:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env # 환경 변수를 저장한 파일 경로
